import { makeSkill } from "./twin-engine";
import type { TwinProfile } from "./twin-types";

export const DEMO_PROFILE: TwinProfile = {
  name: "Alex Johnson",
  degree: "B.Sc Artificial Intelligence & Machine Learning",
  department: "AI & ML",
  year: "3rd Year",
  college: "Northline Institute of Technology",
  skills: [
    makeSkill("Python", "Advanced", 75),
    makeSkill("HTML/CSS", "Advanced", 80),
    makeSkill("SQL", "Intermediate", 65),
    makeSkill("Machine Learning", "Intermediate", 60),
    makeSkill("Java", "Intermediate", 55),
    makeSkill("Git", "Intermediate", 58),
    makeSkill("Deep Learning", "Beginner", 35),
    makeSkill("React", "Beginner", 30),
  ],
  projects: [
    {
      id: "pr1",
      title: "CNN Image Classifier",
      description: "Convolutional network classifying 10 object categories with augmentation and confusion-matrix analysis.",
      tech: "Python, TensorFlow, OpenCV",
      deployed: false,
    },
    {
      id: "pr2",
      title: "Student Performance Predictor",
      description: "Regression pipeline predicting semester results from attendance, internal marks and study habits.",
      tech: "Python, scikit-learn, pandas",
      deployed: true,
    },
    {
      id: "pr3",
      title: "AI Career Assistant",
      description: "Rule-based advisor that maps student skills to job role requirements and suggests learning steps.",
      tech: "Python, Streamlit, SQL",
      deployed: false,
    },
  ],
  experience: {
    internships: ["Data Analyst Intern — Vertex Analytics (2 months, dashboards & SQL reporting)"],
    certifications: ["Machine Learning Specialization — Coursera", "SQL for Data Science — IBM"],
    achievements: ["2nd place, Inter-college AI Hackathon", "Department topper, Semester 4"],
  },
  interests: ["AI", "Data Science", "Computer Vision", "NLP"],
  targetRole: "AI Engineer",
  timelineMonths: 6,
  hoursPerDay: 2,
  shortTermGoal: "Land an AI/ML internship within 3 months",
  longTermGoal: "Become an AI Engineer building production computer-vision systems",
  createdAt: new Date().toISOString(),
  baselineSkills: {
    Python: 55,
    "HTML/CSS": 70,
    SQL: 50,
    "Machine Learning": 42,
    Java: 50,
    Git: 40,
    "Deep Learning": 20,
    React: 25,
  },
  baselineReadiness: 42,
  completedTasks: ["p1t3", "p1t2"],
  completedDays: [1, 2, 3, 4, 5],
  memories: [
    {
      id: "m1",
      text: "You said you prefer project-based learning over long video courses.",
      tag: "behaviour",
      at: new Date().toISOString(),
    },
    {
      id: "m2",
      text: "You asked whether to learn React or Deep Learning first — your twin recommended Deep Learning.",
      tag: "conversation",
      at: new Date().toISOString(),
    },
  ],
};

export const SKILL_LIBRARY = [
  "Python",
  "Java",
  "C++",
  "SQL",
  "HTML/CSS",
  "JavaScript",
  "React",
  "Node.js",
  "Machine Learning",
  "Deep Learning",
  "PyTorch",
  "TensorFlow",
  "NLP",
  "OpenCV",
  "Statistics",
  "Power BI",
  "Excel",
  "Docker",
  "Model Deployment",
  "MLOps",
  "Git",
  "API Integration",
  "Experimentation",
  "Storytelling",
];

export const INTEREST_LIBRARY = [
  "AI",
  "Data Science",
  "Web Development",
  "Computer Vision",
  "NLP",
  "Robotics",
  "Generative AI",
  "Cloud",
  "Cybersecurity",
  "Product Design",
];
