/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareerRouteImport } from './routes/career'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SkillGapRouteImport } from './routes/skill-gap'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as TwinRouteImport } from './routes/twin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillGapRoute = SkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinRoute = TwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/career': typeof CareerRoute
  '/dashboard': typeof DashboardRoute
  '/mentor': typeof MentorRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
  '/roadmap': typeof RoadmapRoute
  '/simulator': typeof SimulatorRoute
  '/skill-gap': typeof SkillGapRoute
  '/skills': typeof SkillsRoute
  '/twin': typeof TwinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/career': typeof CareerRoute
  '/dashboard': typeof DashboardRoute
  '/mentor': typeof MentorRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
  '/roadmap': typeof RoadmapRoute
  '/simulator': typeof SimulatorRoute
  '/skill-gap': typeof SkillGapRoute
  '/skills': typeof SkillsRoute
  '/twin': typeof TwinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/career': typeof CareerRoute
  '/dashboard': typeof DashboardRoute
  '/mentor': typeof MentorRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
  '/roadmap': typeof RoadmapRoute
  '/simulator': typeof SimulatorRoute
  '/skill-gap': typeof SkillGapRoute
  '/skills': typeof SkillsRoute
  '/twin': typeof TwinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/career'
    | '/dashboard'
    | '/mentor'
    | '/plan'
    | '/progress'
    | '/roadmap'
    | '/simulator'
    | '/skill-gap'
    | '/skills'
    | '/twin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/career'
    | '/dashboard'
    | '/mentor'
    | '/plan'
    | '/progress'
    | '/roadmap'
    | '/simulator'
    | '/skill-gap'
    | '/skills'
    | '/twin'
  id:
    | '__root__'
    | '/'
    | '/career'
    | '/dashboard'
    | '/mentor'
    | '/plan'
    | '/progress'
    | '/roadmap'
    | '/simulator'
    | '/skill-gap'
    | '/skills'
    | '/twin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareerRoute: typeof CareerRoute
  DashboardRoute: typeof DashboardRoute
  MentorRoute: typeof MentorRoute
  PlanRoute: typeof PlanRoute
  ProgressRoute: typeof ProgressRoute
  RoadmapRoute: typeof RoadmapRoute
  SimulatorRoute: typeof SimulatorRoute
  SkillGapRoute: typeof SkillGapRoute
  SkillsRoute: typeof SkillsRoute
  TwinRoute: typeof TwinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-gap': {
      id: '/skill-gap'
      path: '/skill-gap'
      fullPath: '/skill-gap'
      preLoaderRoute: typeof SkillGapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareerRoute: CareerRoute,
  DashboardRoute: DashboardRoute,
  MentorRoute: MentorRoute,
  PlanRoute: PlanRoute,
  ProgressRoute: ProgressRoute,
  RoadmapRoute: RoadmapRoute,
  SimulatorRoute: SimulatorRoute,
  SkillGapRoute: SkillGapRoute,
  SkillsRoute: SkillsRoute,
  TwinRoute: TwinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
